import os
import time
from pathlib import Path
from dotenv import load_dotenv
from google import genai

# 1. Setup paths
BASE_DIR = Path(__file__).resolve().parent
WIKI_DIR = BASE_DIR / "wiki"
SYNTHESIS_DIR = WIKI_DIR / "synthesis"

# 2. Load environment and initialize
load_dotenv(BASE_DIR / ".env")
client = genai.Client()

def get_critique_context():
    """Aggregates wiki content with a focus on baselines and the boundary concept."""
    context = ""
    for file in WIKI_DIR.rglob("*.md"):
        # We want to exclude previous synthesis reports to avoid circular logic
        if "synthesis" in str(file) or "LINT" in file.name:
            continue
        with open(file, "r", encoding="utf-8", errors="ignore") as f:
            context += f"\n--- FILE: {file.name} ---\n{f.read()}\n"
    return context

def run_critique():
    print("Gathering evidence from the wiki...")
    context = get_critique_context()
    
    # The prompt explicitly feeds the UniKG-RAG metrics to Gemini
    # to evaluate the other 9 papers.
    critique_prompt = f"""
    You are a Senior Research Reviewer. Using the provided wiki context, 
    write a Technical Critique titled 'The Reification Tax: Why Baselines Fail at Structural Boundaries'.

    Your analysis must address these specific quantitative metrics from UniKG-RAG:
    1. **Path Inflation (1.70x)**: Explain how reification in ToG or GNN-RAG turns a 1-hop fact into a 3-hop traversal.
    2. **Semantic Opacity (24.6%)**: Discuss the 'vacuous nodes' generated by triple-based reification that confuse LLM reasoning.
    3. **Retrieval Fragmentation**: Detail why top-k retrievers in baselines fail to co-retrieve qualifiers ($ \Omega $).

    Structure the report as:
    - **Executive Summary**: The fundamental flaw of 'Structural Homogeneity'.
    - **Baseline Post-Mortem**: A breakdown of why ToG, GNN-RAG, and RoG fail when $ 37.5\% $ of questions cross a boundary.
    - **Domain-Specific Failures**: Why temporal agents (TimeR4, Temp-r1) cannot generalize to non-temporal qualifiers.
    - **Conclusion**: Why 'Universal Fact Atomicity' is the only viable path forward.

    WIKI CONTEXT:
    {context}
    """

    print("Gemini is performing the technical critique...")
    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=critique_prompt
    )

    # Save the critique
    SYNTHESIS_DIR.mkdir(exist_ok=True)
    output_file = SYNTHESIS_DIR / "technical_critique.md"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(response.text)
    
    print(f"Critique complete! Review it at: {output_file}")

if __name__ == "__main__":
    run_critique()